# GitHub Sponsors and donation configurations
# Documentation: https://docs.github.com/admin/identity-and-access-management/managing-iam-for-your-enterprise/configuring-sponsorship-buttons

github: [andiupn]
ko_fi: andiupn
trakteer: andi_upn
custom: ['https://saweria.co/andiupn']
